### Import Package:

In [1]:
import pandas as pd
import pyqsar
from pyqsar import data_tools as dt  #widget for data
from sklearn.preprocessing import MinMaxScaler #Standardisation of data
import pickle
import numpy as np

### Check Model Data:

In [4]:
f= ".\\f1_45rmc_csv\\fs9_feature table.csv"
data = pd.read_csv(f)
xdata = data.drop(["pIC50"],axis=1)
xdata.head()

,AATS8e,AATS8i,ATSC6p,BCUTc-1h,ETA_Eta_F_L,ETA_dEpsilon_D,MATS6c,MATS6s,khs.dsN
0,0.863854,0.451902,0.332383,0.586994,0.487191,0.644339,0.596701,0.493799,0
1,0.485725,0.401111,0.295976,0.998009,0.061697,0.597389,0.732675,0.540075,0
2,0.501960,0.690100,0.481598,0.582411,0.000000,0.924522,0.250352,0.095721,0
3,0.758594,0.499000,0.850883,0.332469,1.000000,0.468521,0.589085,0.360222,0
4,0.675848,0.412258,0.474789,0.585968,0.202401,0.663835,0.620063,0.261223,0

In [6]:
with open("datad9.pickle", "rb") as f:
    model = pickle.load(f)
xd = xdata.values
result = np.around(model.predict(xd),3)
pd.DataFrame(result).to_csv(".\pIC50report_d9.csv",index=False)

### Get New Xdata:

In [21]:
#get columns name:
columns_data = xdata.columns.tolist() 
columns_data.remove('khs.dsN')
columns_data.append("ndsN")

In [22]:
filename = ".\\peptideDresult.csv" #open peptides descriptors data
newdata = pd.read_csv(filename)

Pdata = pd.DataFrame(newdata ,columns=columns_data)
Pdata.head()

,AATS8e,AATS8p,ATSC6p,BCUTc-1h,ETA_dEpsilon_D,GATS8p,MATS6c,MATS6s,MDEC-33,VE2_Dt,nHsOH,ndsN
0,7.973716,1.205776,-3.521707,0.276691,0.13071,1.004022,0.147597,-0.059291,12.701891,0.004707,2.0,0.0
1,8.048470,1.136994,-1.101650,0.276788,0.13271,1.027163,0.175981,-0.067682,15.228669,0.010771,2.0,0.0
2,7.931590,1.234943,-2.137723,0.276664,0.12242,0.981324,0.182667,-0.005594,12.515676,0.019573,1.0,0.0
3,7.961725,1.218526,-2.518457,0.276651,0.13470,0.993491,0.133290,-0.067300,9.968118,0.008695,2.0,0.0
4,7.984557,1.155491,-5.515791,0.276565,0.13242,1.045701,0.178257,0.002936,0.000000,0.006390,2.0,0.0

### Standardisation of Data:

In [23]:
header = list(Pdata.columns.values)
scaler = MinMaxScaler()
P_data_scaled = scaler.fit_transform(Pdata)
Pdata = pd.DataFrame(P_data_scaled, columns=header)
Pdata.head()

,AATS8e,AATS8p,ATSC6p,BCUTc-1h,ETA_dEpsilon_D,GATS8p,MATS6c,MATS6s,MDEC-33,VE2_Dt,nHsOH,ndsN
0,0.401130,0.846960,0.227404,0.063722,0.591806,0.418295,0.549536,0.376173,0.490280,0.222538,0.25,0.0
1,0.514559,0.563772,0.503386,0.080013,0.611840,0.454937,0.730038,0.334707,0.587811,0.512930,0.25,0.0
2,0.337211,0.967045,0.385233,0.059204,0.508765,0.382355,0.772554,0.641537,0.483093,0.934469,0.00,0.0
3,0.382935,0.899454,0.341814,0.057067,0.631774,0.401620,0.458548,0.336593,0.384759,0.413531,0.25,0.0
4,0.417580,0.639926,0.000000,0.042660,0.608935,0.484291,0.744509,0.683689,0.000000,0.303173,0.25,0.0

### Predict activity of Novel compounds:

In [26]:
#open the model and predict new data:
with open("datad12.pickle", "rb") as f:
    model = pickle.load(f)

px = Pdata.values
result = np.around(model.predict(px),3)
pd.DataFrame(result).to_csv(".\ppIC50report_d12.csv",index=False)